// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PGSH.Infrastructure.Database;

#nullable disable

namespace PGSH.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260901203137_CnpnIntakeYearsBackfill")]
    partial class CnpnIntakeYearsBackfill
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EmployeeService", b =>
                {
                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid");

                    b.HasKey("ServiceId", "StaffId");

                    b.HasIndex("StaffId");

                    b.ToTable("EmployeeService", "public");
                });

            modelBuilder.Entity("PGSH.Domain.Audit.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("PerformedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_AuditLog_CreatedAt");

                    b.HasIndex("PerformedByUserId")
                        .HasDatabaseName("IX_AuditLog_PerformedBy");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("IX_AuditLog_Entity");

                    b.ToTable("AuditLogs", "public");
                });

            modelBuilder.Entity("PGSH.Domain.Calendar.Holiday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("EndDate");

                    b.HasIndex("StartDate", "Name")
                        .IsUnique();

                    b.ToTable("Holidays", "public");
                });

            modelBuilder.Entity("PGSH.Domain.Common.Utils.Level", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AcademicProgram")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Year", "AcademicProgram")
                        .IsUnique()
                        .HasDatabaseName("IX_Level_Year_Program");

                    b.ToTable("Levels", "public");
                });

            modelBuilder.Entity("PGSH.Domain.Hospitals.Center", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CenterType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Centers", "public");
                });

            modelBuilder.Entity("PGSH.Domain.Hospitals.Hospital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CenterId")
                        .HasColumnType("integer");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("HospitalType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CenterId");

                    b.ToTable("Hospitals", "public");
                });

            modelBuilder.Entity("PGSH.Domain.Hospitals.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("HospitalId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ServiceChefId")
                        .HasColumnType("uuid");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Specialty")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("HospitalId");

                    b.HasIndex("ServiceChefId");

                    b.ToTable("Services", "public");
                });

            modelBuilder.Entity("PGSH.Domain.Hospitals.ServiceChefAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ServiceId")
                        .IsUnique()
                        .HasFilter("\"EndDate\" IS NULL");

                    b.ToTable("ServiceChefAssignment", "public");
                });

            modelBuilder.Entity("PGSH.Domain.Hospitals.ServiceLevelCapacity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<int>("LevelId")
                        .HasColumnType("integer");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.HasIndex("ServiceId", "LevelId")
                        .IsUnique();

                    b.ToTable("ServiceLevelCapacities", "public");
                });

            modelBuilder.Entity("PGSH.Domain.Registrations.AcademicGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicYearId")
                        .HasColumnType("integer");

                    b.Property<string>("GeographicZone")
                        .HasColumnType("text");

                    b.Property<int>("GroupNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("LevelId")
                        .HasColumnType("integer");

                    b.Property<string>("RotationGroup")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.HasIndex("AcademicYearId", "LevelId", "GroupNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_AcademicGroup_Year_Level_Number");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("AcademicYearId", "LevelId", "GroupNumber"), false);

                    b.HasIndex("AcademicYearId", "LevelId", "Label")
                        .IsUnique()
                        .HasDatabaseName("IX_AcademicGroup_Year_Level_Label");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("AcademicYearId", "LevelId", "Label"), false);

                    b.ToTable("AcademicGroups", "public");
                });

            modelBuilder.Entity("PGSH.Domain.Registrations.AcademicYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("IsCurrent")
                        .IsUnique()
                        .HasDatabaseName("IX_AcademicYear_IsCurrent")
                        .HasFilter("\"IsCurrent\"");

                    b.HasIndex("Label")
                        .IsUnique();

                    b.ToTable("AcademicYears", "public");
                });

            modelBuilder.Entity("PGSH.Domain.Registrations.FinalYearEntryWaiver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AcademicYearId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("GrantedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("GrantedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OutstandingAtGrant")
                        .HasColumnType("integer");

                    b.Property<string>("OutstandingSummary")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AcademicYearId");

                    b.HasIndex("StudentId", "AcademicYearId")
                        .IsUnique()
                        .HasDatabaseName("IX_FinalYearEntryWaiver_Student_Year");

                    b.ToTable("FinalYearEntryWaivers", "public");
                });

            modelBuilder.Entity("PGSH.Domain.Registrations.PriorEnrolment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly?>("EquivalenceDate")
                        .HasColumnType("date");

                    b.Property<string>("EquivalenceReference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("LastLevelYearCompleted")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("RecordedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RecordedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RegistrationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationId")
                        .IsUnique()
                        .HasDatabaseName("IX_PriorEnrolment_Registration");

                    b.ToTable("PriorEnrolments", "public");
                });

            modelBuilder.Entity("PGSH.Domain.Registrations.Registration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AcademicGroupId")
                        .HasColumnType("integer");

                    b.Property<int>("AcademicYearId")
                        .HasColumnType("integer");

                    b.Property<string>("CnpnSource")
                        .HasColumnType("text");

                    b.Property<int?>("CnpnVersionId")
                        .HasColumnType("integer");

                    b.Property<int>("LevelId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("OutcomeRecordedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OutcomeSource")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RegistrationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AcademicGroupId");

                    b.HasIndex("CnpnVersionId");

                    b.HasIndex("LevelId");

                    b.HasIndex("AcademicYearId", "LevelId")
                        .HasDatabaseName("IX_Registration_Year_Level");

                    b.HasIndex("StudentId", "AcademicYearId")
                        .IsUnique()
                        .HasDatabaseName("IX_Registration_Student_Year");

                    b.ToTable("Registrations", "public");
                });

            modelBuilder.Entity("PGSH.Domain.Stages.AttendanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("ServicePeriodId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ServicePeriodId", "Date")
                        .IsUnique()
                        .HasDatabaseName("IX_AttendanceRecord_Period_Date");

                    b.ToTable("AttendanceRecords", "public");
                });

            modelBuilder.Entity("PGSH.Domain.Stages.CnpnLevelEffectivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CnpnVersionId")
                        .HasColumnType("integer");

                    b.Property<int>("FromAcademicYearId")
                        .HasColumnType("integer");

                    b.Property<int>("LevelId")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("RecordedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FromAcademicYearId");

                    b.HasIndex("CnpnVersionId", "LevelId")
                        .IsUnique()
                        .HasDatabaseName("IX_CnpnLevelEffectivity_Version_Level");

                    b.HasIndex("LevelId", "FromAcademicYearId")
                        .IsUnique()
                        .HasDatabaseName("IX_CnpnLevelEffectivity_Level_FromYear");

                    b.ToTable("CnpnLevelEffectivities", "public");
                });

            modelBuilder.Entity("PGSH.Domain.Stages.CnpnVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AcademicProgram")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("AppliesToEntrantsFromAcademicYearId")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Reference")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("TotalYears")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AppliesToEntrantsFromAcademicYearId");

                    b.HasIndex("AcademicProgram", "Code")
                        .IsUnique()
                        .HasDatabaseName("IX_CnpnVersion_Program_Code");

                    b.ToTable("CnpnVersions", "public");
                });

            modelBuilder.Entity("PGSH.Domain.Stages.Cohort", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicGroupId")
                        .HasColumnType("integer");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("StageId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AcademicGroupId");

                    b.HasIndex("StageId");

                    b.ToTable("Cohorts", "public");
                });

            modelBuilder.Entity("PGSH.Domain.Stages.CohortMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CohortId")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid>("InternshipAssignmentId")
                        .HasColumnType("uuid");

                    b.Property<int?>("OriginalCohortId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("TransferReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TransferType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CohortId");

                    b.HasIndex("InternshipAssignmentId")
                        .HasDatabaseName("IX_CohortMembership_AssignmentId");

                    b.ToTable("CohortMembership", "public");
                });

            modelBuilder.Entity("PGSH.Domain.Stages.CohortSlotAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CohortId")
                        .HasColumnType("integer");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<int>("StageSlotId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("StageSlotId");

                    b.HasIndex("CohortId", "StageSlotId")
                        .IsUnique()
                        .HasDatabaseName("IX_CohortSlotAssignment_Cohort_Slot");

                    b.ToTable("CohortSlotAssignments", "public");
                });

            modelBuilder.Entity("PGSH.Domain.Stages.Curriculum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CnpnVersionId")
                        .HasColumnType("integer");

                    b.Property<int>("LevelId")
                        .HasColumnType("integer");

                    b.Property<string>("Reference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.HasIndex("CnpnVersionId", "LevelId")
                        .IsUnique()
                        .HasDatabaseName("IX_Curriculum_Version_Level");

                    b.ToTable("Curriculums", "public");
                });

            modelBuilder.Entity("PGSH.Domain.Stages.CurriculumStage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Coefficient")
                        .HasColumnType("integer");

                    b.Property<int>("CurriculumId")
                        .HasColumnType("integer");

                    b.Property<int>("DurationInDays")
                        .HasColumnType("integer");

                    b.Property<int>("StageId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StageId");

                    b.HasIndex("CurriculumId", "StageId")
                        .IsUnique()
                        .HasDatabaseName("IX_CurriculumStage_Curriculum_Stage");

                    b.ToTable("CurriculumStages", "public");
                });

            modelBuilder.Entity("PGSH.Domain.Stages.Delocalization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DemandeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ServicePeriodId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ServicePeriodId")
                        .IsUnique()
                        .HasDatabaseName("IX_Delocalization_ServicePeriodId");

                    b.ToTable("Delocalization", "public");
                });

            modelBuilder.Entity("PGSH.Domain.Stages.InternshipAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentCohortId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("FinalScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<Guid>("RegistrationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Result")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CurrentCohortId")
                        .HasDatabaseName("IX_InternshipAssignment_CohortId");

                    b.HasIndex("RegistrationId")
                        .HasDatabaseName("IX_InternshipAssignment_RegistrationId");

                    b.ToTable("InternshipAssignments", "public");
                });

            modelBuilder.Entity("PGSH.Domain.Stages.ObjectiveScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("Outcome")
                        .HasColumnType("text");

                    b.Property<int?>("Score")
                        .HasColumnType("integer");

                    b.Property<Guid>("ServiceEvaluationId")
                        .HasColumnType("uuid");

                    b.Property<int>("StageObjectiveId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ServiceEvaluationId");

                    b.HasIndex("StageObjectiveId");

                    b.ToTable("ObjectiveScores", "public");
                });

            modelBuilder.Entity("PGSH.Domain.Stages.PeriodPause", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("ResumeDate")
                        .HasColumnType("date");

                    b.Property<Guid>("ServicePeriodId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ServicePeriodId")
                        .HasDatabaseName("IX_PeriodPause_ServicePeriodId");

                    b.ToTable("PeriodPause", "public");
                });

            modelBuilder.Entity("PGSH.Domain.Stages.ServiceEvaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EvaluatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EvaluatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("FicheReference")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Outcome")
                        .HasColumnType("text");

                    b.Property<Guid>("ServicePeriodId")
                        .HasColumnType("uuid");

                    b.Property<string>("SupervisorComment")
                        .HasColumnType("text");

                    b.Property<decimal?>("TotalScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("ServicePeriodId")
                        .IsUnique();

                    b.ToTable("ServiceEvaluation", "public");
                });

            modelBuilder.Entity("PGSH.Domain.Stages.ServicePeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("CohortSlotAssignmentId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid>("InternshipAssignmentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDelocalized")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsInterrupted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsStarted")
                        .HasColumnType("boolean");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CohortSlotAssignmentId");

                    b.HasIndex("InternshipAssignmentId")
                        .HasDatabaseName("IX_ServicePeriod_AssignmentId");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("IX_ServicePeriod_ServiceId");

                    b.ToTable("ServicePeriods", "public");
                });

            modelBuilder.Entity("PGSH.Domain.Stages.ServicePeriodSlotCoverage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CohortSlotAssignmentId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ServicePeriodId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ServicePeriodId");

                    b.HasIndex("CohortSlotAssignmentId", "ServicePeriodId")
                        .IsUnique()
                        .HasDatabaseName("IX_ServicePeriodSlotCoverage_Cell_Period");

                    b.ToTable("ServicePeriodSlotCoverage", "public");
                });

            modelBuilder.Entity("PGSH.Domain.Stages.Stage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Coefficient")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DurationInDays")
                        .HasColumnType("integer");

                    b.Property<int>("LevelId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RotationMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("PerPeriod");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.ToTable("Stages", "public");
                });

            modelBuilder.Entity("PGSH.Domain.Stages.StageObjective", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("StageId")
                        .HasColumnType("integer");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StageId");

                    b.ToTable("StageObjectives", "public");
                });

            modelBuilder.Entity("PGSH.Domain.Stages.StageSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicYearId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Label")
                        .HasColumnType("text");

                    b.Property<int>("PeriodNumber")
                        .HasColumnType("integer");

                    b.Property<int>("StageId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("AcademicYearId");

                    b.HasIndex("StageId", "AcademicYearId", "PeriodNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_StageSlot_Stage_Year_Period");

                    b.ToTable("StageSlots", "public");
                });

            modelBuilder.Entity("PGSH.Domain.Students.History", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HistoryData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Histories", "public");
                });

            modelBuilder.Entity("PGSH.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CIN")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<DateTime>("IdentityLinkedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdentityProviderId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PlaceOfBirth")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdentityProviderId")
                        .IsUnique()
                        .HasFilter("\"IdentityProviderId\" IS NOT NULL");

                    b.ToTable("Users", "public");

                    b.HasDiscriminator<string>("UserType").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("StageAllowedServices", b =>
                {
                    b.Property<int>("StageId")
                        .HasColumnType("integer");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.HasKey("StageId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("StageId", "ServiceId")
                        .HasDatabaseName("IX_StageAllowedServices_Stage_Service");

                    b.ToTable("StageAllowedServices", "public");
                });

            modelBuilder.Entity("PGSH.Domain.Employees.Employee", b =>
                {
                    b.HasBaseType("PGSH.Domain.Users.User");

                    b.Property<int>("Grade")
                        .HasColumnType("integer");

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PPR")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("Position")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("PvSignatureDate")
                        .HasColumnType("date");

                    b.Property<int?>("WorkPlace")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Employee");
                });

            modelBuilder.Entity("PGSH.Domain.Students.Student", b =>
                {
                    b.HasBaseType("PGSH.Domain.Users.User");

                    b.Property<string>("AcademicProgram")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Academy")
                        .HasColumnType("integer");

                    b.Property<decimal>("AccessGrade")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("AgreementType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Appogee")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("BacSeries")
                        .HasColumnType("integer");

                    b.Property<string>("BacYear")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("CNE")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("CnpnAssignmentIsInferred")
                        .HasColumnType("boolean");

                    b.Property<int?>("CnpnVersionId")
                        .HasColumnType("integer");

                    b.Property<int?>("Province")
                        .HasColumnType("integer");

                    b.Property<int?>("Ranking")
                        .HasColumnType("integer");

                    b.HasIndex("Appogee")
                        .IsUnique()
                        .HasDatabaseName("IX_Student_Appogee")
                        .HasFilter("\"Appogee\" IS NOT NULL");

                    b.HasIndex("CNE")
                        .IsUnique()
                        .HasDatabaseName("IX_Student_CNE")
                        .HasFilter("\"CNE\" IS NOT NULL");

                    b.HasIndex("CnpnVersionId");

                    b.HasDiscriminator().HasValue("Student");
                });

            modelBuilder.Entity("EmployeeService", b =>
                {
                    b.HasOne("PGSH.Domain.Hospitals.Service", null)
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PGSH.Domain.Employees.Employee", null)
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PGSH.Domain.Hospitals.Center", b =>
                {
                    b.OwnsOne("PGSH.Domain.Common.Utils.Localization", "LocalisationMaps", b1 =>
                        {
                            b1.Property<int>("CenterId")
                                .HasColumnType("integer");

                            b1.Property<string>("x")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("X");

                            b1.Property<string>("y")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("Y");

                            b1.Property<string>("z")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("Z");

                            b1.HasKey("CenterId");

                            b1.ToTable("Centers", "public");

                            b1.WithOwner()
                                .HasForeignKey("CenterId");
                        });

                    b.Navigation("LocalisationMaps");
                });

            modelBuilder.Entity("PGSH.Domain.Hospitals.Hospital", b =>
                {
                    b.HasOne("PGSH.Domain.Hospitals.Center", "Center")
                        .WithMany("Hospitals")
                        .HasForeignKey("CenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("PGSH.Domain.Common.Utils.Localization", "LocalisationMaps", b1 =>
                        {
                            b1.Property<int>("HospitalId")
                                .HasColumnType("integer");

                            b1.Property<string>("x")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("X");

                            b1.Property<string>("y")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("Y");

                            b1.Property<string>("z")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("Z");

                            b1.HasKey("HospitalId");

                            b1.ToTable("Hospitals", "public");

                            b1.WithOwner()
                                .HasForeignKey("HospitalId");
                        });

                    b.Navigation("Center");

                    b.Navigation("LocalisationMaps");
                });

            modelBuilder.Entity("PGSH.Domain.Hospitals.Service", b =>
                {
                    b.HasOne("PGSH.Domain.Hospitals.Hospital", "Hospital")
                        .WithMany("services")
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PGSH.Domain.Employees.Employee", "ServiceChef")
                        .WithMany()
                        .HasForeignKey("ServiceChefId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("PGSH.Domain.Common.Utils.Localization", "LocalisationMaps", b1 =>
                        {
                            b1.Property<int>("ServiceId")
                                .HasColumnType("integer");

                            b1.Property<string>("x")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("X");

                            b1.Property<string>("y")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("Y");

                            b1.Property<string>("z")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("Z");

                            b1.HasKey("ServiceId");

                            b1.ToTable("Services", "public");

                            b1.WithOwner()
                                .HasForeignKey("ServiceId");
                        });

                    b.Navigation("Hospital");

                    b.Navigation("LocalisationMaps");

                    b.Navigation("ServiceChef");
                });

            modelBuilder.Entity("PGSH.Domain.Hospitals.ServiceChefAssignment", b =>
                {
                    b.HasOne("PGSH.Domain.Employees.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PGSH.Domain.Hospitals.Service", "Service")
                        .WithMany("ChefHistory")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("PGSH.Domain.Hospitals.ServiceLevelCapacity", b =>
                {
                    b.HasOne("PGSH.Domain.Common.Utils.Level", "Level")
                        .WithMany()
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PGSH.Domain.Hospitals.Service", "Service")
                        .WithMany("LevelCapacities")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("PGSH.Domain.Registrations.AcademicGroup", b =>
                {
                    b.HasOne("PGSH.Domain.Registrations.AcademicYear", "AcademicYear")
                        .WithMany("Groups")
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PGSH.Domain.Common.Utils.Level", "Level")
                        .WithMany()
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AcademicYear");

                    b.Navigation("Level");
                });

            modelBuilder.Entity("PGSH.Domain.Registrations.FinalYearEntryWaiver", b =>
                {
                    b.HasOne("PGSH.Domain.Registrations.AcademicYear", "AcademicYear")
                        .WithMany()
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PGSH.Domain.Students.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcademicYear");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PGSH.Domain.Registrations.PriorEnrolment", b =>
                {
                    b.HasOne("PGSH.Domain.Registrations.Registration", "Registration")
                        .WithMany()
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("PGSH.Domain.Registrations.Registration", b =>
                {
                    b.HasOne("PGSH.Domain.Registrations.AcademicGroup", "AcademicGroup")
                        .WithMany("Registrations")
                        .HasForeignKey("AcademicGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PGSH.Domain.Registrations.AcademicYear", "AcademicYear")
                        .WithMany()
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PGSH.Domain.Stages.CnpnVersion", "CnpnVersion")
                        .WithMany()
                        .HasForeignKey("CnpnVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PGSH.Domain.Common.Utils.Level", "Level")
                        .WithMany()
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PGSH.Domain.Students.Student", "Student")
                        .WithMany("Registrations")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("PGSH.Domain.Registrations.FailureReasons", "failureReasons", b1 =>
                        {
                            b1.Property<Guid>("RegistrationId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("Cheat")
                                .HasColumnType("boolean");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<string>("Notes")
                                .IsRequired()
                                .HasColumnType("jsonb");

                            b1.HasKey("RegistrationId");

                            b1.ToTable("Registrations", "public");

                            b1.WithOwner()
                                .HasForeignKey("RegistrationId");
                        });

                    b.Navigation("AcademicGroup");

                    b.Navigation("AcademicYear");

                    b.Navigation("CnpnVersion");

                    b.Navigation("Level");

                    b.Navigation("Student");

                    b.Navigation("failureReasons");
                });

            modelBuilder.Entity("PGSH.Domain.Stages.AttendanceRecord", b =>
                {
                    b.HasOne("PGSH.Domain.Stages.ServicePeriod", "ServicePeriod")
                        .WithMany("Attendance")
                        .HasForeignKey("ServicePeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServicePeriod");
                });

            modelBuilder.Entity("PGSH.Domain.Stages.CnpnLevelEffectivity", b =>
                {
                    b.HasOne("PGSH.Domain.Stages.CnpnVersion", "CnpnVersion")
                        .WithMany("LevelEffectivities")
                        .HasForeignKey("CnpnVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PGSH.Domain.Registrations.AcademicYear", "FromAcademicYear")
                        .WithMany()
                        .HasForeignKey("FromAcademicYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PGSH.Domain.Common.Utils.Level", "Level")
                        .WithMany()
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CnpnVersion");

                    b.Navigation("FromAcademicYear");

                    b.Navigation("Level");
                });

            modelBuilder.Entity("PGSH.Domain.Stages.CnpnVersion", b =>
                {
                    b.HasOne("PGSH.Domain.Registrations.AcademicYear", "AppliesToEntrantsFromAcademicYear")
                        .WithMany()
                        .HasForeignKey("AppliesToEntrantsFromAcademicYearId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AppliesToEntrantsFromAcademicYear");
                });

            modelBuilder.Entity("PGSH.Domain.Stages.Cohort", b =>
                {
                    b.HasOne("PGSH.Domain.Registrations.AcademicGroup", "AcademicGroup")
                        .WithMany("Cohorts")
                        .HasForeignKey("AcademicGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PGSH.Domain.Stages.Stage", "Stage")
                        .WithMany()
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcademicGroup");

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("PGSH.Domain.Stages.CohortMembership", b =>
                {
                    b.HasOne("PGSH.Domain.Stages.Cohort", "Cohort")
                        .WithMany()
                        .HasForeignKey("CohortId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PGSH.Domain.Stages.InternshipAssignment", null)
                        .WithMany("MembershipHistory")
                        .HasForeignKey("InternshipAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cohort");
                });

            modelBuilder.Entity("PGSH.Domain.Stages.CohortSlotAssignment", b =>
                {
                    b.HasOne("PGSH.Domain.Stages.Cohort", "Cohort")
                        .WithMany("SlotAssignments")
                        .HasForeignKey("CohortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PGSH.Domain.Hospitals.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PGSH.Domain.Stages.StageSlot", "StageSlot")
                        .WithMany("Assignments")
                        .HasForeignKey("StageSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cohort");

                    b.Navigation("Service");

                    b.Navigation("StageSlot");
                });

            modelBuilder.Entity("PGSH.Domain.Stages.Curriculum", b =>
                {
                    b.HasOne("PGSH.Domain.Stages.CnpnVersion", "CnpnVersion")
                        .WithMany("Curricula")
                        .HasForeignKey("CnpnVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PGSH.Domain.Common.Utils.Level", "Level")
                        .WithMany()
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CnpnVersion");

                    b.Navigation("Level");
                });

            modelBuilder.Entity("PGSH.Domain.Stages.CurriculumStage", b =>
                {
                    b.HasOne("PGSH.Domain.Stages.Curriculum", "Curriculum")
                        .WithMany("Stages")
                        .HasForeignKey("CurriculumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PGSH.Domain.Stages.Stage", "Stage")
                        .WithMany()
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Curriculum");

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("PGSH.Domain.Stages.Delocalization", b =>
                {
                    b.HasOne("PGSH.Domain.Stages.ServicePeriod", "ServicePeriod")
                        .WithOne("Delocalization")
                        .HasForeignKey("PGSH.Domain.Stages.Delocalization", "ServicePeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServicePeriod");
                });

            modelBuilder.Entity("PGSH.Domain.Stages.InternshipAssignment", b =>
                {
                    b.HasOne("PGSH.Domain.Stages.Cohort", "Cohort")
                        .WithMany("Assignments")
                        .HasForeignKey("CurrentCohortId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PGSH.Domain.Registrations.Registration", "Registration")
                        .WithMany("InternshipAssignments")
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cohort");

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("PGSH.Domain.Stages.ObjectiveScore", b =>
                {
                    b.HasOne("PGSH.Domain.Stages.ServiceEvaluation", "ServiceEvaluation")
                        .WithMany("ObjectiveScores")
                        .HasForeignKey("ServiceEvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PGSH.Domain.Stages.StageObjective", "StageObjective")
                        .WithMany()
                        .HasForeignKey("StageObjectiveId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ServiceEvaluation");

                    b.Navigation("StageObjective");
                });

            modelBuilder.Entity("PGSH.Domain.Stages.PeriodPause", b =>
                {
                    b.HasOne("PGSH.Domain.Stages.ServicePeriod", "ServicePeriod")
                        .WithMany("Pauses")
                        .HasForeignKey("ServicePeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServicePeriod");
                });

            modelBuilder.Entity("PGSH.Domain.Stages.ServiceEvaluation", b =>
                {
                    b.HasOne("PGSH.Domain.Stages.ServicePeriod", "ServicePeriod")
                        .WithOne("Evaluation")
                        .HasForeignKey("PGSH.Domain.Stages.ServiceEvaluation", "ServicePeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServicePeriod");
                });

            modelBuilder.Entity("PGSH.Domain.Stages.ServicePeriod", b =>
                {
                    b.HasOne("PGSH.Domain.Stages.CohortSlotAssignment", "CohortSlotAssignment")
                        .WithMany()
                        .HasForeignKey("CohortSlotAssignmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PGSH.Domain.Stages.InternshipAssignment", "InternshipAssignment")
                        .WithMany("ServicePeriods")
                        .HasForeignKey("InternshipAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PGSH.Domain.Hospitals.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CohortSlotAssignment");

                    b.Navigation("InternshipAssignment");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("PGSH.Domain.Stages.ServicePeriodSlotCoverage", b =>
                {
                    b.HasOne("PGSH.Domain.Stages.CohortSlotAssignment", "CohortSlotAssignment")
                        .WithMany()
                        .HasForeignKey("CohortSlotAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PGSH.Domain.Stages.ServicePeriod", "ServicePeriod")
                        .WithMany("SlotCoverage")
                        .HasForeignKey("ServicePeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CohortSlotAssignment");

                    b.Navigation("ServicePeriod");
                });

            modelBuilder.Entity("PGSH.Domain.Stages.Stage", b =>
                {
                    b.HasOne("PGSH.Domain.Common.Utils.Level", "Level")
                        .WithMany()
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Level");
                });

            modelBuilder.Entity("PGSH.Domain.Stages.StageObjective", b =>
                {
                    b.HasOne("PGSH.Domain.Stages.Stage", "Stage")
                        .WithMany("Objectives")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("PGSH.Domain.Stages.StageSlot", b =>
                {
                    b.HasOne("PGSH.Domain.Registrations.AcademicYear", "AcademicYear")
                        .WithMany()
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PGSH.Domain.Stages.Stage", "Stage")
                        .WithMany("Slots")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcademicYear");

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("PGSH.Domain.Students.History", b =>
                {
                    b.HasOne("PGSH.Domain.Students.Student", "Student")
                        .WithMany("HistoryEntries")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PGSH.Domain.Users.User", b =>
                {
                    b.OwnsOne("PGSH.Domain.Users.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("Country")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("FullAddress")
                                .IsRequired()
                                .HasMaxLength(250)
                                .HasColumnType("character varying(250)");

                            b1.Property<string>("HouseNumber")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("Street")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("ZIP")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.HasKey("UserId");

                            b1.ToTable("Users", "public");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("PGSH.Domain.Users.Status", "Status", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CivilStatus")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("NationalityStatus")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.HasKey("UserId");

                            b1.ToTable("Users", "public");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Address");

                    b.Navigation("Status")
                        .IsRequired();
                });

            modelBuilder.Entity("StageAllowedServices", b =>
                {
                    b.HasOne("PGSH.Domain.Hospitals.Service", null)
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PGSH.Domain.Stages.Stage", null)
                        .WithMany()
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PGSH.Domain.Students.Student", b =>
                {
                    b.HasOne("PGSH.Domain.Stages.CnpnVersion", "CnpnVersion")
                        .WithMany()
                        .HasForeignKey("CnpnVersionId");

                    b.Navigation("CnpnVersion");
                });

            modelBuilder.Entity("PGSH.Domain.Hospitals.Center", b =>
                {
                    b.Navigation("Hospitals");
                });

            modelBuilder.Entity("PGSH.Domain.Hospitals.Hospital", b =>
                {
                    b.Navigation("services");
                });

            modelBuilder.Entity("PGSH.Domain.Hospitals.Service", b =>
                {
                    b.Navigation("ChefHistory");

                    b.Navigation("LevelCapacities");
                });

            modelBuilder.Entity("PGSH.Domain.Registrations.AcademicGroup", b =>
                {
                    b.Navigation("Cohorts");

                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("PGSH.Domain.Registrations.AcademicYear", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("PGSH.Domain.Registrations.Registration", b =>
                {
                    b.Navigation("InternshipAssignments");
                });

            modelBuilder.Entity("PGSH.Domain.Stages.CnpnVersion", b =>
                {
                    b.Navigation("Curricula");

                    b.Navigation("LevelEffectivities");
                });

            modelBuilder.Entity("PGSH.Domain.Stages.Cohort", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("SlotAssignments");
                });

            modelBuilder.Entity("PGSH.Domain.Stages.Curriculum", b =>
                {
                    b.Navigation("Stages");
                });

            modelBuilder.Entity("PGSH.Domain.Stages.InternshipAssignment", b =>
                {
                    b.Navigation("MembershipHistory");

                    b.Navigation("ServicePeriods");
                });

            modelBuilder.Entity("PGSH.Domain.Stages.ServiceEvaluation", b =>
                {
                    b.Navigation("ObjectiveScores");
                });

            modelBuilder.Entity("PGSH.Domain.Stages.ServicePeriod", b =>
                {
                    b.Navigation("Attendance");

                    b.Navigation("Delocalization");

                    b.Navigation("Evaluation");

                    b.Navigation("Pauses");

                    b.Navigation("SlotCoverage");
                });

            modelBuilder.Entity("PGSH.Domain.Stages.Stage", b =>
                {
                    b.Navigation("Objectives");

                    b.Navigation("Slots");
                });

            modelBuilder.Entity("PGSH.Domain.Stages.StageSlot", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("PGSH.Domain.Students.Student", b =>
                {
                    b.Navigation("HistoryEntries");

                    b.Navigation("Registrations");
                });
#pragma warning restore 612, 618
        }
    }
}
