// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PGSH.Infrastructure.Database;

#nullable disable

namespace PGSH.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EmployeeService", b =>
                {
                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid");

                    b.HasKey("ServiceId", "StaffId");

                    b.HasIndex("StaffId");

                    b.ToTable("EmployeeService", "public");
                });

            modelBuilder.Entity("PGSH.Domain.Common.Utils.Level", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AcademicProgram")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Level", "public");
                });

            modelBuilder.Entity("PGSH.Domain.Hospitals.Center", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CenterType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Centers", "public");
                });

            modelBuilder.Entity("PGSH.Domain.Hospitals.Hospital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CenterId")
                        .HasColumnType("integer");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("HospitalType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CenterId");

                    b.ToTable("Hospitals", "public");
                });

            modelBuilder.Entity("PGSH.Domain.Hospitals.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("HospitalId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ServiceChefId")
                        .HasColumnType("uuid");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HospitalId");

                    b.HasIndex("ServiceChefId");

                    b.ToTable("Services", "public");
                });

            modelBuilder.Entity("PGSH.Domain.Registrations.Registration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("AcademicYear")
                        .HasColumnType("date");

                    b.Property<int>("LevelId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.HasIndex("StudentId");

                    b.ToTable("Registrations", "public");
                });

            modelBuilder.Entity("PGSH.Domain.Stages.AssignmentPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssignementId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("End")
                        .HasColumnType("date");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Start")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("AssignementId");

                    b.HasIndex("ServiceId");

                    b.ToTable("AssignmentPeriods", "public");
                });

            modelBuilder.Entity("PGSH.Domain.Stages.InternshipAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("PlannedEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PlannedStart")
                        .HasColumnType("date");

                    b.Property<Guid>("RegistrationId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("StageGroupId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationId");

                    b.HasIndex("StageGroupId");

                    b.ToTable("InternshipAssignments", "public");
                });

            modelBuilder.Entity("PGSH.Domain.Stages.Stage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Coefficient")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DurationInDays")
                        .HasColumnType("integer");

                    b.Property<int>("LevelId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.ToTable("Stages", "public");
                });

            modelBuilder.Entity("PGSH.Domain.Stages.StageGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("StageId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StageId");

                    b.ToTable("StagesGroup", "public");
                });

            modelBuilder.Entity("PGSH.Domain.Students.History", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HistoryData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("History", "public");
                });

            modelBuilder.Entity("PGSH.Domain.Todos.TodoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<List<string>>("Labels")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TodoItems", "public");
                });

            modelBuilder.Entity("PGSH.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CIN")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PlaceOfBirth")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", "public");

                    b.HasDiscriminator<string>("UserType").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PGSH.Domain.Employees.Employee", b =>
                {
                    b.HasBaseType("PGSH.Domain.Users.User");

                    b.Property<int>("Grade")
                        .HasColumnType("integer");

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PPR")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("Position")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("PvSignatureDate")
                        .HasColumnType("date");

                    b.Property<int?>("WorkPlace")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Employee");
                });

            modelBuilder.Entity("PGSH.Domain.Students.Student", b =>
                {
                    b.HasBaseType("PGSH.Domain.Users.User");

                    b.Property<string>("AcademicProgram")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Academy")
                        .HasColumnType("integer");

                    b.Property<decimal>("AccessGrade")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("AgreementType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Appogee")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("BacSeries")
                        .HasColumnType("integer");

                    b.Property<string>("BacYear")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("CNE")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("Province")
                        .HasColumnType("integer");

                    b.Property<int?>("Ranking")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Student");
                });

            modelBuilder.Entity("EmployeeService", b =>
                {
                    b.HasOne("PGSH.Domain.Hospitals.Service", null)
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PGSH.Domain.Employees.Employee", null)
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PGSH.Domain.Hospitals.Center", b =>
                {
                    b.OwnsOne("PGSH.Domain.Common.Utils.Localization", "LocalisationMaps", b1 =>
                        {
                            b1.Property<int>("CenterId")
                                .HasColumnType("integer");

                            b1.Property<string>("x")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("X");

                            b1.Property<string>("y")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("Y");

                            b1.Property<string>("z")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("Z");

                            b1.HasKey("CenterId");

                            b1.ToTable("Centers", "public");

                            b1.WithOwner()
                                .HasForeignKey("CenterId");
                        });

                    b.Navigation("LocalisationMaps");
                });

            modelBuilder.Entity("PGSH.Domain.Hospitals.Hospital", b =>
                {
                    b.HasOne("PGSH.Domain.Hospitals.Center", "Center")
                        .WithMany("Hospitals")
                        .HasForeignKey("CenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("PGSH.Domain.Common.Utils.Localization", "LocalisationMaps", b1 =>
                        {
                            b1.Property<int>("HospitalId")
                                .HasColumnType("integer");

                            b1.Property<string>("x")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("X");

                            b1.Property<string>("y")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("Y");

                            b1.Property<string>("z")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("Z");

                            b1.HasKey("HospitalId");

                            b1.ToTable("Hospitals", "public");

                            b1.WithOwner()
                                .HasForeignKey("HospitalId");
                        });

                    b.Navigation("Center");

                    b.Navigation("LocalisationMaps");
                });

            modelBuilder.Entity("PGSH.Domain.Hospitals.Service", b =>
                {
                    b.HasOne("PGSH.Domain.Hospitals.Hospital", "Hospital")
                        .WithMany("services")
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PGSH.Domain.Employees.Employee", "ServiceChef")
                        .WithMany()
                        .HasForeignKey("ServiceChefId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Hospital");

                    b.Navigation("ServiceChef");
                });

            modelBuilder.Entity("PGSH.Domain.Registrations.Registration", b =>
                {
                    b.HasOne("PGSH.Domain.Common.Utils.Level", "Level")
                        .WithMany()
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PGSH.Domain.Students.Student", "Student")
                        .WithMany("registrations")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("PGSH.Domain.Registrations.FailureReasons", "failureReasons", b1 =>
                        {
                            b1.Property<Guid>("RegistrationId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("Cheat")
                                .HasColumnType("boolean");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<string>("Notes")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("RegistrationId");

                            b1.ToTable("Registrations", "public");

                            b1.WithOwner()
                                .HasForeignKey("RegistrationId");
                        });

                    b.Navigation("Level");

                    b.Navigation("Student");

                    b.Navigation("failureReasons");
                });

            modelBuilder.Entity("PGSH.Domain.Stages.AssignmentPeriod", b =>
                {
                    b.HasOne("PGSH.Domain.Stages.InternshipAssignment", "InternshipAssignment")
                        .WithMany("Periods")
                        .HasForeignKey("AssignementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PGSH.Domain.Hospitals.Service", "Service")
                        .WithMany("assignmentPeriods")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InternshipAssignment");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("PGSH.Domain.Stages.InternshipAssignment", b =>
                {
                    b.HasOne("PGSH.Domain.Registrations.Registration", "Registration")
                        .WithMany("InternshipAssignments")
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PGSH.Domain.Stages.StageGroup", "StageGroup")
                        .WithMany("internshipAssignments")
                        .HasForeignKey("StageGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Registration");

                    b.Navigation("StageGroup");
                });

            modelBuilder.Entity("PGSH.Domain.Stages.Stage", b =>
                {
                    b.HasOne("PGSH.Domain.Common.Utils.Level", "Level")
                        .WithMany()
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Level");
                });

            modelBuilder.Entity("PGSH.Domain.Stages.StageGroup", b =>
                {
                    b.HasOne("PGSH.Domain.Stages.Stage", "Stage")
                        .WithMany()
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("PGSH.Domain.Students.History", b =>
                {
                    b.HasOne("PGSH.Domain.Students.Student", "Student")
                        .WithMany("history")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PGSH.Domain.Todos.TodoItem", b =>
                {
                    b.HasOne("PGSH.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PGSH.Domain.Users.User", b =>
                {
                    b.OwnsOne("PGSH.Domain.Users.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("Country")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("FullAddress")
                                .IsRequired()
                                .HasMaxLength(250)
                                .HasColumnType("character varying(250)");

                            b1.Property<string>("HouseNumber")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("Street")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("ZIP")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.HasKey("UserId");

                            b1.ToTable("Users", "public");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("PGSH.Domain.Users.Status", "Status", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CivilStatus")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("NationalityStatus")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.HasKey("UserId");

                            b1.ToTable("Users", "public");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Address");

                    b.Navigation("Status")
                        .IsRequired();
                });

            modelBuilder.Entity("PGSH.Domain.Hospitals.Center", b =>
                {
                    b.Navigation("Hospitals");
                });

            modelBuilder.Entity("PGSH.Domain.Hospitals.Hospital", b =>
                {
                    b.Navigation("services");
                });

            modelBuilder.Entity("PGSH.Domain.Hospitals.Service", b =>
                {
                    b.Navigation("assignmentPeriods");
                });

            modelBuilder.Entity("PGSH.Domain.Registrations.Registration", b =>
                {
                    b.Navigation("InternshipAssignments");
                });

            modelBuilder.Entity("PGSH.Domain.Stages.InternshipAssignment", b =>
                {
                    b.Navigation("Periods");
                });

            modelBuilder.Entity("PGSH.Domain.Stages.StageGroup", b =>
                {
                    b.Navigation("internshipAssignments");
                });

            modelBuilder.Entity("PGSH.Domain.Students.Student", b =>
                {
                    b.Navigation("history");

                    b.Navigation("registrations");
                });
#pragma warning restore 612, 618
        }
    }
}
