using PGSH.Infrastructure.Database;

namespace PGSH.Tests.Postgres;

/// <summary>
/// The minimum catalogue a delete-behaviour test needs, seeded through the <b>shared</b>
/// <see cref="TestHarness"/> helpers rather than a second set built here.
/// </summary>
/// <remarks>
/// ⚠ Those helpers set explicit integer keys. That is fine on PostgreSQL because EF maps these keys
/// as <c>GENERATED BY DEFAULT AS IDENTITY</c>, which accepts a supplied value — worth stating,
/// because <c>GENERATED ALWAYS</c> would refuse every fixture in this repository and the failure
/// would look like a broken test rather than a mapping decision. The sequence is left behind the
/// explicit ids, so a test that mixes supplied and generated keys in one table must supply its own.
/// </remarks>
internal static class PostgresSeed
{
    internal sealed record Catalog(int StageId, int CohortId);

    public static async Task<Catalog> CatalogAsync(PostgresDatabase database)
    {
        await using var db = database.Connect();

        var stage = db.SeedCatalog();
        var cohort = db.SeedCohort(stage, groupId: 1, groupLabel: "G1");

        await db.SaveChangesAsync();

        return new Catalog(stage.Id, cohort.Id);
    }
}
